### PR TITLE
Fix issue 1 and the behavior of the development option

### PR DESCRIPTION
**Pull request by breezeight**
#1

### CODE REVIEW

**Comment by rjocoleman** [comment]
thanks! Is this middleman v4 or v3?

**Comment by breezeight** [comment]
Hi! v4

**Comment by breezeight** [comment]
Hi @rjocoleman if you want to support both middleman 3 and 4 you could add travis. This is a reference http://schneems.com/post/50991826838/testing-against-multiple-rails-versions/

**Comment by rjocoleman** [comment]
@breezeight this extension was written for middleman v3.. It's not in the README though.. 
Installed users against v3 will have compatibility issues.

Travis isn't going to be useful without actual tests to run against! 😊

**Comment by rjocoleman** [comment]
thanks @breezeight v1.0.0 has now been released:

For middleman v4.x you'll want in your `Gemfile`

``` ruby
  gem 'middleman-google-tag-manager', '~> 1'
```

(Updated the syntax above sorry!)

**Pull request merged**
